{
  "createProject": {
    "403": ["The project code has been taken"],
    "default": ["something went wrong when creating new project"]
  },
  "login": {
    "400": ["Your account has been disabled."],
    "401": ["Your username and/or password do not match"],
    "500": [
      "An issue was encountered while trying to login, please try again later."
    ],
    "default": [
      "An issue was encountered while trying to login, please try again later."
    ]
  },
  "resetPassword": {
    "400": ["Your old password is not correct"],
    "403": ["This reset password is not permitted."],
    "406": [
      "The password format is not valid. The password must be 11-30 characters, at least 1 uppercase, 1 lowercase, 1 number and 1 special character(-_!%&/()=?*+#,.;)."
    ],
    "500": [
      "Internal Error occurs when trying to reset password, please try again later"
    ],
    "default": ["Something wrong when resetting your password"]
  },
  "forgotPassword": {
    "403": ["This reset password link is invalid or expired."],
    "406": [
      "The password format is not valid. The password must be 11-30 characters, at least 1 uppercase, 1 lowercase, 1 number and 1 special character(-_!%&/()=?*+#,.;)."
    ],
    "404": ["This username does not exist."],
    "500": [
      "Internal Error occurs when trying to reset password, please try again later"
    ],
    "default": ["Something wrong when sending reset password email."]
  },
  "forgotUserName": {
    "404": ["This email address does not exist."],
    "500": [
      "Internal Error occurs when trying to get username, please try again later"
    ],
    "default": ["something wrong when send your username through email"]
  },
  "checkToken": {
    "400": ["This reset password link is not valid."],
    "500": [
      "Internal Error occurs when trying to reset password, please try again later"
    ],
    "default": ["something wrong when verifiying your identity with the link."]
  },
  "resetForgottenPassword": {
    "403": ["This reset password link is invalid or expired."],
    "400": [
      "The password format is not valid, please check the password requirement."
    ],
    "500": [
      "Internal Error occurs when trying to reset password, please try again later"
    ],
    "default": ["something wrong when resetting your password"]
  },
  "refresh": {
    "403": [
      "Something went wrong while trying to refresh, please try again later"
    ],
    "500": [
      "Something went wrong while trying to refresh, please try again later"
    ],
    "default": [
      "Something went wrong while trying to refresh, please try again later"
    ]
  },
  "parseInviteHashAPI": {
    "401": ["Sorry, your invitation is expired."],
    "404": ["Sorry, your invitation is not found."],
    "500": [
      "Internal Error occurs when trying to fetch invitation details please try again later"
    ],
    "default": [
      "Internal Error occurs when trying to fetch invitation details please try again later"
    ]
  },
  "uploadFileApi": {
    "403": ["file already exists within the project."],
    "500": [
      "An Internal Error has occurred while attempting to upload file",
      "Please try again later."
    ],
    "502": [
      "An Internal Error has occurred while attempting to upload file",
      "Please try again later."
    ],
    "default": ["Something went wrong when uploading"]
  },
  "uploadRequestFail": {
    "default": ["Failed to upload", "please try again"]
  },

  "getRawFilesAPI": {
    "403": ["Sorry, you don't have access to get raw files from this project"],
    "500": [
      "Internal Error occurs when trying to get raw files, please try again later"
    ],
    "404": ["Sorry, Cannot find raw files in project"],
    "default": ["Something went wrong when getting raw files"]
  },
  "getChildrenDataset": {
    "403": [
      "Sorry, you don't have access to get children dataset from this project"
    ],
    "500": [
      "Internal Error occurs when trying to get children dataset, please try again later"
    ],
    "default": ["Something went wrong when getting children dataset"]
  },
  "traverseFoldersContainersAPI": {
    "403": [
      "You do not have the correct permissions to access this folder, please check your account settings or contact an administrator"
    ],
    "500": [
      "Something went wrong while trying to access this folder, please try again later."
    ],
    "404": [
      "We were unable to locate the folder you requested, please try again later."
    ],
    "default": [
      "Something went wrong while trying to access this folder, please try again later."
    ]
  },
  "getFilesByTypeAPI": {
    "403": [
      "Sorry, you are not authorized to access processed files at this time."
    ],
    "500": [
      "Something went wrong while trying to process files, please try again later."
    ],
    "default": [
      "Something went wrong while trying to process files, please try again later."
    ]
  },
  "downloadFilesAPI": {
    "403": ["Sorry, you are not authorized to download files."],
    "500": [
      "Something went wrong while trying to download files, please try again later."
    ],
    "default": [
      "Something went wrong while trying to download files, please try again later."
    ]
  },
  "processingFile": {
    "default": ["failed to process file", "please upload again later"]
  },
  "preUpload": {
    "403": ["Sorry,", "cannot be uploaded."],
    "409": [
      "A file by the name of",
      "already exists in the project, please choose a different name for your file before uploading."
    ],
    "500": [
      "Something went wrong while trying to upload the file",
      "please try again later"
    ],
    "default": ["Failed to upload"]
  },
  "selfRegistration": {
    "400": [
      "Something went wrong while trying to create your account, please try again later"
    ],
    "401": ["Invite link is expired"],
    "500": [
      "Something went wrong while trying to create your account, please try again later"
    ],
    "default": [
      "Something went wrong while trying to create your account, please try again later"
    ]
  },
  "inviteUser": {
    "403": ["Unable to invite user", "please try again later"],
    "404": [
      "Something went wrong when trying to invite user",
      "to the project, please try again later"
    ],
    "500": [
      "Something went wrong when trying to invite user",
      "to the project, please try again later"
    ],
    "default": [
      "Something went wrong when trying to invite user",
      "to the project, please try again later"
    ]
  },
  "checkEmailExistAPI": {
    "403": ["User by email", "already exists in the project"],
    "500": [
      "An Internal Error occurred while validating user list. Please try again later."
    ],
    "default": [
      "An Internal Error occurred while validating user list. Please try again later."
    ]
  },
  "checkUserPlatformRole": {
    "403": [
      "Something went wrong when checking user's role on platform.  Please try again later."
    ],
    "500": [
      "Something went wrong when checking user's role on platform. Please try again later."
    ],
    "default": [
      "Something went wrong when checking user's role on platform.  Please try again later."
    ]
  },
  "addUsertoDataSet": {
    "403": [
      "is already a member of this project, to modify permissions for",
      "you can update their role in the user management module"
    ],
    "500": [
      "Something went wrong when trying to invite user",
      "to the project, please try again later"
    ]
  },
  "changeRoleInDataset": {
    "403": [
      "Something went wrong while trying to change the role for",
      "please try again later."
    ],
    "404": [
      "Something went wrong while trying to change the role for",
      "please try again later."
    ],
    "500": [
      "Something went wrong while trying to change the role for",
      "please try again later."
    ]
  },
  "getUsersOnDataset": {
    "403": [
      "You do not have the correct permissions to view users in this project, please check your account settings or contact an administrator"
    ],
    "404": [
      "Something went wrong while trying to fetch the user list for this project, please try again later"
    ],
    "500": [
      "Something went wrong while trying to fetch the user list for this project, please try again later"
    ]
  },
  "removeUserFromDataset": {
    "403": [
      "You do not have the correct permissions to remove user",
      "from this project, please check your account settings or contact an administrator"
    ],
    "404": [
      "Something went wrong while trying to remove a user from this project, please try again later"
    ],
    "500": [
      "Something went wrong while trying to remove a user from this project, please try again later"
    ]
  },
  "restoreUserFromDataset": {
    "403": [
      "You do not have the correct permissions to resotre user",
      "from this project, please check your account settings or contact an administrator"
    ],
    "404": [
      "Something went wrong while trying to restore a user from this project, please try again later"
    ],
    "500": [
      "Something went wrong while trying to restore a user from this project, please try again later"
    ]
  },
  "getDataset": {
    "default": ["Internal Error: Unable to load projects list"]
  },
  "listAllContainersPermission": {
    "401": [
      "You do not have the correct permissions to edit user roles on this project, please check your account settings or contact an administrator"
    ],
    "404": [
      "We were unable to locate the project while trying to set containers permissions, please try again later."
    ],
    "default": [
      "An Internal Error occurred when trying to set containers permission"
    ]
  },
  "contactUsAPI": {
    "401": [
      "You do not have the correct permissions submit a request, please contact an administrator or email us directly at vre-support@charite.de"
    ],
    "404": [
      "Something went wrong while trying to submit your support request, please try again later or email us directly at vre-support@charite.de"
    ],
    "default": [
      "Something went wrong while trying to submit your support request, please try again later or email us directly at vre-support@charite.de"
    ]
  },
  "inviteUserApi": {
    "400": ["User by email", "already exists in the platform."],
    "default": [
      "Something went wrong when trying to invite user to platform. Please try again later"
    ]
  },
  "getPortalUsers": {
    "400": ["Cannot get the users list."],
    "default": [
      "Something went wrong when trying to get users list. Please try again later."
    ]
  },
  "updateUserStatusAPI": {
    "400": ["Cannot update the users status."],
    "default": [
      "Something went wrong when trying to update users status. Please try again later."
    ]
  },
  "getInvitationsAPI": {
    "400": ["Cannot get the invitations."],
    "default": [
      "Something went wrong when trying to get invitations. Please try again later."
    ]
  }
}
